class InterpretationData {
  InterpretationData._();

  static const sunSign = {
    'Aries': 'Your Aries Sun blazes with initiative and courage. You are a natural pioneer who thrives on challenge and competition. Your core identity is driven by the need to forge new paths and assert your independence.',
    'Taurus': 'Your Taurus Sun is grounded in sensory experience and material security. You possess an unwavering determination and a deep appreciation for beauty, comfort, and the finer things in life.',
    'Gemini': 'Your Gemini Sun is fueled by intellectual curiosity and versatility. You are a natural communicator who thrives on variety, social connection, and the constant exchange of ideas.',
    'Cancer': 'Your Cancer Sun is rooted in emotional depth and nurturing instinct. You are profoundly connected to home, family, and the emotional undercurrents that flow beneath the surface of life.',
    'Leo': 'Your Leo Sun radiates warmth, creativity, and magnetic charisma. You are born to shine and inspire, with a generous heart that seeks recognition through authentic self-expression.',
    'Virgo': 'Your Virgo Sun is oriented toward service, analysis, and practical perfection. You possess a keen eye for detail and a deep desire to improve systems, health, and the quality of everyday life.',
    'Libra': 'Your Libra Sun seeks harmony, beauty, and balanced partnership. You are a natural diplomat who values fairness and strives to create aesthetic and social equilibrium in all relationships.',
    'Scorpio': 'Your Scorpio Sun operates with penetrating intensity and transformative power. You are drawn to the depths of experience, seeking truth beneath surfaces and wielding remarkable emotional resilience.',
    'Sagittarius': 'Your Sagittarius Sun is animated by philosophical curiosity and adventurous optimism. You are a seeker of truth and meaning, driven to explore the world through travel, learning, and spiritual inquiry.',
    'Capricorn': 'Your Capricorn Sun is built on ambition, discipline, and strategic long-term vision. You are a master builder who earns authority through persistence and practical achievement.',
    'Aquarius': 'Your Aquarius Sun pulses with innovative vision and humanitarian ideals. You are a forward-thinker who challenges convention and advocates for collective progress and individual freedom.',
    'Pisces': 'Your Pisces Sun dissolves boundaries between self and cosmos. You are a compassionate dreamer with profound artistic sensitivity and an intuitive connection to the collective unconscious.',
  };

  static const moonSign = {
    'Aries': 'Your Aries Moon processes emotions with urgency and directness. You need emotional independence and respond to feelings with immediate action. Anger flares fast but dissipates quickly.',
    'Taurus': 'Your Taurus Moon craves emotional stability and sensory comfort. You process feelings slowly and deeply, finding security through routine, physical touch, and material groundedness.',
    'Gemini': 'Your Gemini Moon intellectualizes emotions and needs verbal processing. You feel most secure when you can talk through your feelings and maintain multiple emotional outlets.',
    'Cancer': 'Your Cancer Moon feels everything deeply and intuitively. You are emotionally absorbent, needing a safe home base to retreat to and nurture your inner world.',
    'Leo': 'Your Leo Moon needs emotional recognition and creative expression. You process feelings dramatically and generously, requiring warmth, appreciation, and an audience for your inner life.',
    'Virgo': 'Your Virgo Moon processes emotions through analysis and practical problem-solving. You feel most secure when life is organized and you can be of service to others.',
    'Libra': 'Your Libra Moon seeks emotional balance and relational harmony. You process feelings through partnership and dialogue, needing beauty and peace in your emotional environment.',
    'Scorpio': 'Your Scorpio Moon experiences emotions with volcanic intensity. You feel everything to the core, possessing remarkable emotional resilience and a need for deep, transformative connections.',
    'Sagittarius': 'Your Sagittarius Moon processes emotions through optimism and philosophical perspective. You need emotional freedom and find comfort in adventure, humor, and expansive experiences.',
    'Capricorn': 'Your Capricorn Moon manages emotions with stoic discipline. You process feelings privately, finding security through achievement and maintaining emotional composure under pressure.',
    'Aquarius': 'Your Aquarius Moon processes emotions through intellectual detachment and group connection. You need emotional independence and find comfort in humanitarian causes and unconventional bonds.',
    'Pisces': 'Your Pisces Moon absorbs the emotional atmosphere of every room. You process feelings through imagination, dreams, and creative expression, needing regular solitude to decompress.',
  };

  static const risingSigns = {
    'Aries': 'With Aries Rising, you project confidence, directness, and competitive energy. First impressions are bold and action-oriented. You approach new situations head-first.',
    'Taurus': 'With Taurus Rising, you project calm stability, sensuality, and dependability. First impressions are grounded and reassuring. You approach life at a deliberate, measured pace.',
    'Gemini': 'With Gemini Rising, you project intellectual curiosity and social agility. First impressions are witty and engaging. You approach new situations with questions and adaptability.',
    'Cancer': 'With Cancer Rising, you project warmth, sensitivity, and protective energy. First impressions are nurturing. You approach new situations with emotional caution and intuitive assessment.',
    'Leo': 'With Leo Rising, you project warmth, magnetism, and natural authority. First impressions are memorable and confident. You approach life as a stage for creative self-expression.',
    'Virgo': 'With Virgo Rising, you project competence, modesty, and analytical precision. First impressions are composed and helpful. You approach new situations with careful observation.',
    'Libra': 'With Libra Rising, you project grace, charm, and diplomatic elegance. First impressions are pleasant and balanced. You approach life seeking beauty and harmonious connection.',
    'Scorpio': 'With Scorpio Rising, you project intensity, mystery, and magnetic presence. First impressions are penetrating. You approach new situations with strategic awareness and emotional depth.',
    'Sagittarius': 'With Sagittarius Rising, you project optimism, enthusiasm, and philosophical breadth. First impressions are jovial and inspiring. You approach life as a grand adventure.',
    'Capricorn': 'With Capricorn Rising, you project authority, maturity, and professional composure. First impressions are serious and capable. You approach life with strategic ambition.',
    'Aquarius': 'With Aquarius Rising, you project uniqueness, intellectual independence, and progressive values. First impressions are unconventional. You approach life as a catalyst for change.',
    'Pisces': 'With Pisces Rising, you project gentleness, artistic sensitivity, and ethereal presence. First impressions are dreamy and compassionate. You approach life with fluid adaptability.',
  };

  static const planetSign = <String, String>{
    'mercury_Aries': 'Mercury in Aries gives you a quick, decisive communication style. You think on your feet and speak directly.',
    'mercury_Taurus': 'Mercury in Taurus gives deliberate, practical thinking. You form opinions slowly but hold them firmly.',
    'mercury_Gemini': 'Mercury in Gemini (its home) gives exceptional verbal agility. Your mind races with ideas and connections.',
    'mercury_Cancer': 'Mercury in Cancer colors thinking with emotional intelligence. You communicate with empathy and intuitive understanding.',
    'mercury_Leo': 'Mercury in Leo gives dramatic, confident expression. You communicate with warmth and creative flair.',
    'mercury_Virgo': 'Mercury in Virgo (its home) gives analytical precision. You think methodically and communicate with clarity.',
    'mercury_Libra': 'Mercury in Libra gives diplomatic, balanced communication. You naturally see multiple perspectives.',
    'mercury_Scorpio': 'Mercury in Scorpio gives penetrating, investigative thinking. You see through surface appearances.',
    'mercury_Sagittarius': 'Mercury in Sagittarius gives expansive, philosophical thinking. You communicate big ideas with enthusiasm.',
    'mercury_Capricorn': 'Mercury in Capricorn gives structured, strategic thinking. You communicate with authority and practical wisdom.',
    'mercury_Aquarius': 'Mercury in Aquarius gives innovative, unconventional thinking. Your ideas are ahead of their time.',
    'mercury_Pisces': 'Mercury in Pisces gives intuitive, imaginative thinking. You communicate through metaphor and feeling.',
    'venus_Aries': 'Venus in Aries loves passionately and pursues directly. In love, you are bold and initiating.',
    'venus_Taurus': 'Venus in Taurus (its home) loves sensually and devotedly. You value physical affection and material comfort in love.',
    'venus_Gemini': 'Venus in Gemini loves through intellectual connection. Variety and stimulating conversation are essential.',
    'venus_Cancer': 'Venus in Cancer loves nurturingly and protectively. Emotional security and family bonds are paramount.',
    'venus_Leo': 'Venus in Leo loves grandly and generously. You need romance, attention, and creative partnership.',
    'venus_Virgo': 'Venus in Virgo loves through service and attention to detail. You show love practically and devotedly.',
    'venus_Libra': 'Venus in Libra (its home) loves harmoniously and beautifully. Partnership equality and aesthetic connection are essential.',
    'venus_Scorpio': 'Venus in Scorpio loves intensely and transformatively. You seek soul-deep bonds and emotional truth.',
    'venus_Sagittarius': 'Venus in Sagittarius loves freely and adventurously. You need space, growth, and shared exploration.',
    'venus_Capricorn': 'Venus in Capricorn loves with commitment and ambition. You build love like a long-term investment.',
    'venus_Aquarius': 'Venus in Aquarius loves unconventionally and intellectually. Freedom and friendship are the foundation of romance.',
    'venus_Pisces': 'Venus in Pisces (exalted) loves unconditionally and romantically. You idealize love and give with boundless compassion.',
    'mars_Aries': 'Mars in Aries (its home) gives raw, direct drive. You pursue goals with fearless initiative.',
    'mars_Taurus': 'Mars in Taurus gives slow, persistent drive. You build steadily toward tangible results.',
    'mars_Gemini': 'Mars in Gemini gives mental agility and multitasking energy. You pursue multiple goals simultaneously.',
    'mars_Cancer': 'Mars in Cancer drives through emotional conviction. Your protective instincts fuel fierce determination.',
    'mars_Leo': 'Mars in Leo gives confident, dramatic drive. You pursue goals with bold creative energy.',
    'mars_Virgo': 'Mars in Virgo gives precise, methodical drive. You achieve through detailed planning and refinement.',
    'mars_Libra': 'Mars in Libra drives through charm and strategy. You achieve goals through diplomatic negotiation.',
    'mars_Scorpio': 'Mars in Scorpio (its home) gives intense, focused drive. You pursue goals with relentless, strategic determination.',
    'mars_Sagittarius': 'Mars in Sagittarius gives enthusiastic, expansive drive. You pursue goals with optimistic boldness.',
    'mars_Capricorn': 'Mars in Capricorn (exalted) gives calculated, ambitious drive. You climb systematically toward long-term objectives.',
    'mars_Aquarius': 'Mars in Aquarius drives through innovation and collective cause. You pursue goals unconventionally.',
    'mars_Pisces': 'Mars in Pisces gives fluid, adaptable drive. You pursue goals through intuition and creative flow.',
  };
}
